window.streams = {
    timeRefresh: 10000,
    stations: [
        {
            name: "Jailson Webradio",
            hash: "jailson",
            description: "Música sem parar",
            logo: "wp-content/plugins/meu-radio-player/assets/jailson_logo.png",
            album: "wp-content/plugins/meu-radio-player/assets/jailson_cover.png",
            cover: "wp-content/plugins/meu-radio-player/assets/jailson_cover.png",
            api: "",
            //api: "api.php?url=https://stream.zeno.fm/yn65fsaurfhvv",
            stream_url: "https://stream.zeno.fm/yn65fsaurfhvv",
            tv_url: "https://eu1.servers10.com:2020/VideoPlayer/8106?autoplay=1",
            server: "",
            program: {
                time: "24/7",
                name: "Jailson Web Radio",
                description: "AO VIVO // ON AIR",
            },
            social: {
                whatsapp: "",
                twitter: "https://twitter.com/",
                tiktok: "",
                youtube: "",
                instagram: "https://www.instagram.com/",
            },
            apps: {
                android: "https://play.google.com/store/apps/details?id=com.jbcast.jwradio",
                ios: "",
            },
        },
        {
            name: "BENDICIÓN STEREO",
            hash: "bendicion",
            description: "Bendecidos para bendecir!",
            logo: "wp-content/plugins/meu-radio-player/assets/default_logo.png",
            album: "wp-content/plugins/meu-radio-player/assets/cover.png",
            cover: "wp-content/plugins/meu-radio-player/assets/cover.png",
            api: "",
            //api: "api.php?url=https://sv2.globalhostlive.com/proxy/bendistereo/stream2",
            api: "https://radioplayer.icu/api5.php?url=https://sv2.globalhostlive.com/proxy/bendistereo/stream2",
            stream_url: "https://sv2.globalhostlive.com/proxy/bendistereo/stream2",
            tv_url: "https://eu1.servers10.com:2020/VideoPlayer/8106?autoplay=1",
            server: "",
            program: {
                time: "11:00",
                name: "Bendición Stereo",
                description: "EN VIVO // ON AIR",
            },
            social: {
                facebook: "https://facebook.com/BendicionStereo",
                twitter: "https://twitter.com/BendiStereo",
                instagram: "https://www.instagram.com/BendiStereo/",
            },
            apps: {
                android: "#",
                ios: "#",
            },
        },
        {
            name: "Rádio Capital Fm",
            hash: "Capital Fm",
            description: "A sua Rádio Pop/Rock!",
            logo: "wp-content/plugins/meu-radio-player/assets/capital_logo.png",
            album: "wp-content/plugins/meu-radio-player/assets/capitallogo_preto.png",
            cover: "wp-content/plugins/meu-radio-player/assets/capitallogo_preto.png",
            //api: "api.php?url=https://stream.zeno.fm/yn65fsaurfhvv",
            api: "",
            stream_url: "https://stm16.xcast.com.br:7208/stream",
            //tv_url: "https://eu1.servers10.com:2020/VideoPlayer/8106?autoplay=1",
            server: "spotify",
            program: {
                time: "00:00",
                name: "Rádio Capital Fm",
                description: "AO VIVO // ON AIR",
            },
            social: {
                facebook: "https://www.facebook.com/CapitalFmRadio/",
                whatsapp: "https://api.whatsapp.com/send/?phone=5522999080266&text=Ol%C3%A1+tudo+bem%3F&type=phone_number&app_absent=0",
                //twitter: "https://twitter.com/",
                //tiktok: "",
                //youtube: "",
                instagram: "https://www.instagram.com/capitalfmradio",
            },
            apps: {
                android: "https://player.xcast.com.br/player-app-multi-plataforma/7208",
                ios: "https://player.xcast.com.br/player-app-multi-plataforma/7208",
            },
        },
    ],
};